### ISSUE TITLE
what AWS_SESSION_TOKEN is used for?

### ISSUE THREAD

**Issue by kuriel-trivu** [Cox-Automotive/aws-ebcli#5]
` docker run -i -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -w /work -v $PWD:/work coxauto/aws-ebcli /bin/bash -c "${CMD}"`

Throws:
`ERROR: InvalidProfileError - The config profile (eb-cli) could not be found`

why needs AWS_SESSION_TOKEN?

secret key and key id are enough.

**Comment by kulinski** [comment]
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html
https://docs.aws.amazon.com/credref/latest/refdocs/setting-global-aws_session_token.html
