### ISSUE TITLE
eb deploy fails after latest image update

### ISSUE THREAD

**Issue by IgorVanian** [Cox-Automotive/aws-ebcli#6]
Hello,

It seems that after the latest docker image update (3 days ago), eb deploy fails
![image](https://user-images.githubusercontent.com/16898357/125419322-43b9b293-900f-445e-a190-df92c208a80b.png)

Anyone is having the same issue here?

**Comment by IgorVanian** [comment]
This issue is due to the latest aws-ebcli upgrade. Symlink directories are not ignored by eb deploy. See https://github.com/aws/aws-elastic-beanstalk-cli/issues/69#issuecomment-879048923

**Comment by kulinski** [comment]
Thanks Igor.  Are you able to work around this issue with the new ebcli version?  Or use the older version of the docker image until AWS Beanstalk team fixes this issue?

**Comment by IgorVanian** [comment]
@kulinski Hi, I bypassed this by always cleaning node_modules/.bin/ folder. Without symlinks it deploys fine. I didn't find any method to pull a previous image from docker :(

**Comment by kulinski** [comment]
The previous version (ebcli 3.15.1) is now available as a tagged version on dockerhub, if you need to use that older version. 
https://hub.docker.com/layers/coxauto/aws-ebcli/3.15.1/images/sha256-5bce892c7fd93c9a8851510a61cc38e2215370753de32c8af41bc13d92ea95f3?context=repo

**Comment by IgorVanian** [comment]
Should be done in https://github.com/aws/aws-elastic-beanstalk-cli/pull/207
